# Generated by Django 3.2.3 on 2022-03-30 01:52

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='Discriptive Name')),
                ('card_image', models.ImageField(upload_to='job_images', verbose_name='Descriptive Image For The Job')),
                ('technical_specification', models.TextField(help_text='format: required, max-1000', max_length=1000, verbose_name='Job Technical Specification')),
                ('terms_and_conditions', models.TextField(help_text='format: required, max-1000', max_length=1000, verbose_name='Job Terms and Conditons')),
                ('payment_terms', models.TextField(help_text='format: required, max-1000', max_length=1000, verbose_name='Job Payment Terms ')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('qualification', models.CharField(max_length=50)),
                ('freelancer_platform', models.CharField(choices=[('up', 'Upwork'), ('FR', 'Fiver'), ('ES', 'Envato Studio'), ('PP', 'PeoplePerHour'), ('TO', 'Toptal'), ('MH', 'MarketerHire'), ('GU', 'Guru'), ('DC', 'DesignCrowd'), ('NX', 'Nexxt'), ('OS', 'OnSite'), ('CS', 'Crewscale')], max_length=100)),
                ('freelancer_link', models.URLField()),
                ('discord_profile_id', models.URLField()),
                ('i_agree_to_terms_and_conditions', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='login_app.user')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='jobportal_app.createjobs')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_applied', to='jobportal_app.createjobs', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_form', to='login_app.user', unique=True)),
            ],
        ),
    ]
