# Generated by Django 4.0.3 on 2022-04-12 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=24, null=True)),
                ('download_speed', models.CharField(max_length=24, null=True)),
                ('upload_speed', models.CharField(max_length=24, null=True)),
            ],
            options={
                'verbose_name_plural': 'Internet Speeds',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedBack', models.TextField(null=True)),
                ('freelancePlatformUrl', models.URLField(null=True)),
                ('applicationName', models.CharField(max_length=132)),
                ('status', models.CharField(default='Pending', max_length=132, null=True)),
                ('applicationlvl', models.CharField(default='HR', max_length=132, null=True)),
                ('country', models.CharField(max_length=132, null=True)),
                ('username', models.CharField(max_length=132, null=True)),
                ('qualification', models.CharField(max_length=132, null=True)),
                ('freelancePlatform', models.CharField(max_length=132, null=True)),
                ('others', models.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'JobApplications',
            },
        ),
        migrations.CreateModel(
            name='NewJobsApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedBack', models.TextField(null=True)),
                ('freelancePlatformUrl', models.URLField(null=True)),
                ('applicationName', models.CharField(max_length=132)),
                ('status', models.CharField(max_length=132, null=True)),
                ('country', models.CharField(max_length=132, null=True)),
                ('username', models.CharField(max_length=132, null=True)),
                ('qualification', models.CharField(max_length=132, null=True)),
                ('freelancePlatform', models.CharField(max_length=132, null=True)),
                ('others', models.JSONField()),
                ('General_Terms_Conditions', models.JSONField()),
                ('Technical_Specifications', models.JSONField()),
                ('Payment_terms', models.JSONField()),
                ('Work_Flow', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'New JobApplications',
            },
        ),
        migrations.CreateModel(
            name='TMCanidateStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_lead_status', models.CharField(max_length=132, null=True)),
                ('team_lead_feedback', models.CharField(max_length=300, null=True)),
                ('JobApplication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Applications.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='HRCandidateStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hr_Status', models.CharField(max_length=132, null=True)),
                ('hr_FeedBack', models.CharField(max_length=300, null=True)),
                ('JobApplication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Applications.jobapplication')),
            ],
            options={
                'verbose_name_plural': 'HR CandidateStatuses',
            },
        ),
        migrations.CreateModel(
            name='AccountsCanidateStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accounts_status', models.CharField(max_length=132, null=True)),
                ('accounts_feedback', models.CharField(max_length=132, null=True)),
                ('JobApplication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Applications.jobapplication')),
            ],
        ),
    ]
