# Generated by Django 4.0.3 on 2022-04-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=24, null=True)),
                ('date', models.DateField()),
                ('task', models.CharField(max_length=132, null=True)),
                ('status', models.CharField(blank=True, choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=24, null=True)),
            ],
        ),
    ]
